D:
cd D:\LVNS\SimplifiedCore\testlibs\managedLibs\RobotsInterfaces\proto
protoc  -I=D:\LVNS\SimplifiedCore\testlibs\managedLibs\RobotsInterfaces\proto\ --csharp_out=D:\LVNS\SimplifiedCore\testlibs\managedLibs\RobotsInterfaces\proto\ D:\LVNS\SimplifiedCore\testlibs\managedLibs\RobotsInterfaces\proto\messages_robocup_ssl_detection.proto --proto_path=.
protoc  -I=D:\LVNS\SimplifiedCore\testlibs\managedLibs\RobotsInterfaces\proto\ --csharp_out=D:\LVNS\SimplifiedCore\testlibs\managedLibs\RobotsInterfaces\proto\ D:\LVNS\SimplifiedCore\testlibs\managedLibs\RobotsInterfaces\proto\messages_robocup_ssl_geometry.proto --proto_path=.
protoc  -I=D:\LVNS\SimplifiedCore\testlibs\managedLibs\RobotsInterfaces\proto\ --csharp_out=D:\LVNS\SimplifiedCore\testlibs\managedLibs\RobotsInterfaces\proto\ D:\LVNS\SimplifiedCore\testlibs\managedLibs\RobotsInterfaces\proto\messages_robocup_ssl_geometry_legacy.proto --proto_path=.
protoc  -I=D:\LVNS\SimplifiedCore\testlibs\managedLibs\RobotsInterfaces\proto\ --csharp_out=D:\LVNS\SimplifiedCore\testlibs\managedLibs\RobotsInterfaces\proto\ D:\LVNS\SimplifiedCore\testlibs\managedLibs\RobotsInterfaces\proto\messages_robocup_ssl_refbox_log.proto --proto_path=.
protoc  -I=D:\LVNS\SimplifiedCore\testlibs\managedLibs\RobotsInterfaces\proto\ --csharp_out=D:\LVNS\SimplifiedCore\testlibs\managedLibs\RobotsInterfaces\proto\ D:\LVNS\SimplifiedCore\testlibs\managedLibs\RobotsInterfaces\proto\messages_robocup_ssl_wrapper.proto --proto_path=.
protoc  -I=D:\LVNS\SimplifiedCore\testlibs\managedLibs\RobotsInterfaces\proto\ --csharp_out=D:\LVNS\SimplifiedCore\testlibs\managedLibs\RobotsInterfaces\proto\ D:\LVNS\SimplifiedCore\testlibs\managedLibs\RobotsInterfaces\proto\messages_robocup_ssl_wrapper_legacy.proto --proto_path=.
protoc  -I=D:\LVNS\SimplifiedCore\testlibs\managedLibs\RobotsInterfaces\proto\ --csharp_out=D:\LVNS\SimplifiedCore\testlibs\managedLibs\RobotsInterfaces\proto\ D:\LVNS\SimplifiedCore\testlibs\managedLibs\RobotsInterfaces\proto\unit.proto --proto_path=.
