// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: messages_robocup_ssl_refbox_log.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from messages_robocup_ssl_refbox_log.proto</summary>
public static partial class MessagesRobocupSslRefboxLogReflection {

  #region Descriptor
  /// <summary>File descriptor for messages_robocup_ssl_refbox_log.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static MessagesRobocupSslRefboxLogReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "CiVtZXNzYWdlc19yb2JvY3VwX3NzbF9yZWZib3hfbG9nLnByb3RvGiRtZXNz",
          "YWdlc19yb2JvY3VwX3NzbF9kZXRlY3Rpb24ucHJvdG8iQwoJTG9nX0ZyYW1l",
          "EiIKBWZyYW1lGAEgASgLMhMuU1NMX0RldGVjdGlvbkZyYW1lEhIKCnJlZmJv",
          "eF9jbWQYAiABKAkiJQoKUmVmYm94X0xvZxIXCgNsb2cYASADKAsyCi5Mb2df",
          "RnJhbWViBnByb3RvMw=="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { global::MessagesRobocupSslDetectionReflection.Descriptor, },
        new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::Log_Frame), global::Log_Frame.Parser, new[]{ "Frame", "RefboxCmd" }, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::Refbox_Log), global::Refbox_Log.Parser, new[]{ "Log" }, null, null, null)
        }));
  }
  #endregion

}
#region Messages
public sealed partial class Log_Frame : pb::IMessage<Log_Frame> {
  private static readonly pb::MessageParser<Log_Frame> _parser = new pb::MessageParser<Log_Frame>(() => new Log_Frame());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<Log_Frame> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::MessagesRobocupSslRefboxLogReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public Log_Frame() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public Log_Frame(Log_Frame other) : this() {
    Frame = other.frame_ != null ? other.Frame.Clone() : null;
    refboxCmd_ = other.refboxCmd_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public Log_Frame Clone() {
    return new Log_Frame(this);
  }

  /// <summary>Field number for the "frame" field.</summary>
  public const int FrameFieldNumber = 1;
  private global::SSL_DetectionFrame frame_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::SSL_DetectionFrame Frame {
    get { return frame_; }
    set {
      frame_ = value;
    }
  }

  /// <summary>Field number for the "refbox_cmd" field.</summary>
  public const int RefboxCmdFieldNumber = 2;
  private string refboxCmd_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string RefboxCmd {
    get { return refboxCmd_; }
    set {
      refboxCmd_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as Log_Frame);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(Log_Frame other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (!object.Equals(Frame, other.Frame)) return false;
    if (RefboxCmd != other.RefboxCmd) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (frame_ != null) hash ^= Frame.GetHashCode();
    if (RefboxCmd.Length != 0) hash ^= RefboxCmd.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (frame_ != null) {
      output.WriteRawTag(10);
      output.WriteMessage(Frame);
    }
    if (RefboxCmd.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(RefboxCmd);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (frame_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Frame);
    }
    if (RefboxCmd.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(RefboxCmd);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(Log_Frame other) {
    if (other == null) {
      return;
    }
    if (other.frame_ != null) {
      if (frame_ == null) {
        frame_ = new global::SSL_DetectionFrame();
      }
      Frame.MergeFrom(other.Frame);
    }
    if (other.RefboxCmd.Length != 0) {
      RefboxCmd = other.RefboxCmd;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          if (frame_ == null) {
            frame_ = new global::SSL_DetectionFrame();
          }
          input.ReadMessage(frame_);
          break;
        }
        case 18: {
          RefboxCmd = input.ReadString();
          break;
        }
      }
    }
  }

}

public sealed partial class Refbox_Log : pb::IMessage<Refbox_Log> {
  private static readonly pb::MessageParser<Refbox_Log> _parser = new pb::MessageParser<Refbox_Log>(() => new Refbox_Log());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<Refbox_Log> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::MessagesRobocupSslRefboxLogReflection.Descriptor.MessageTypes[1]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public Refbox_Log() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public Refbox_Log(Refbox_Log other) : this() {
    log_ = other.log_.Clone();
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public Refbox_Log Clone() {
    return new Refbox_Log(this);
  }

  /// <summary>Field number for the "log" field.</summary>
  public const int LogFieldNumber = 1;
  private static readonly pb::FieldCodec<global::Log_Frame> _repeated_log_codec
      = pb::FieldCodec.ForMessage(10, global::Log_Frame.Parser);
  private readonly pbc::RepeatedField<global::Log_Frame> log_ = new pbc::RepeatedField<global::Log_Frame>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public pbc::RepeatedField<global::Log_Frame> Log {
    get { return log_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as Refbox_Log);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(Refbox_Log other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if(!log_.Equals(other.log_)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    hash ^= log_.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    log_.WriteTo(output, _repeated_log_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    size += log_.CalculateSize(_repeated_log_codec);
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(Refbox_Log other) {
    if (other == null) {
      return;
    }
    log_.Add(other.log_);
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          log_.AddEntriesFrom(input, _repeated_log_codec);
          break;
        }
      }
    }
  }

}

#endregion


#endregion Designer generated code
