// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: messages_robocup_ssl_geometry_legacy.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace RoboCup2014Legacy.Geometry {

  /// <summary>Holder for reflection information generated from messages_robocup_ssl_geometry_legacy.proto</summary>
  public static partial class MessagesRobocupSslGeometryLegacyReflection {

    #region Descriptor
    /// <summary>File descriptor for messages_robocup_ssl_geometry_legacy.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MessagesRobocupSslGeometryLegacyReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiptZXNzYWdlc19yb2JvY3VwX3NzbF9nZW9tZXRyeV9sZWdhY3kucHJvdG8S",
            "GlJvYm9DdXAyMDE0TGVnYWN5Lkdlb21ldHJ5GiNtZXNzYWdlc19yb2JvY3Vw",
            "X3NzbF9nZW9tZXRyeS5wcm90byKKAwoVU1NMX0dlb21ldHJ5RmllbGRTaXpl",
            "EhIKCmxpbmVfd2lkdGgYASABKAUSFAoMZmllbGRfbGVuZ3RoGAIgASgFEhMK",
            "C2ZpZWxkX3dpZHRoGAMgASgFEhYKDmJvdW5kYXJ5X3dpZHRoGAQgASgFEhUK",
            "DXJlZmVyZWVfd2lkdGgYBSABKAUSEgoKZ29hbF93aWR0aBgGIAEoBRISCgpn",
            "b2FsX2RlcHRoGAcgASgFEhcKD2dvYWxfd2FsbF93aWR0aBgIIAEoBRIcChRj",
            "ZW50ZXJfY2lyY2xlX3JhZGl1cxgJIAEoBRIWCg5kZWZlbnNlX3JhZGl1cxgK",
            "IAEoBRIXCg9kZWZlbnNlX3N0cmV0Y2gYCyABKAUSIwobZnJlZV9raWNrX2Zy",
            "b21fZGVmZW5zZV9kaXN0GAwgASgFEikKIXBlbmFsdHlfc3BvdF9mcm9tX2Zp",
            "ZWxkX2xpbmVfZGlzdBgNIAEoBRIjChtwZW5hbHR5X2xpbmVfZnJvbV9zcG90",
            "X2Rpc3QYDiABKAUigwEKEFNTTF9HZW9tZXRyeURhdGESQAoFZmllbGQYASAB",
            "KAsyMS5Sb2JvQ3VwMjAxNExlZ2FjeS5HZW9tZXRyeS5TU0xfR2VvbWV0cnlG",
            "aWVsZFNpemUSLQoFY2FsaWIYAiADKAsyHi5TU0xfR2VvbWV0cnlDYW1lcmFD",
            "YWxpYnJhdGlvbmIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::MessagesRobocupSslGeometryReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::RoboCup2014Legacy.Geometry.SSL_GeometryFieldSize), global::RoboCup2014Legacy.Geometry.SSL_GeometryFieldSize.Parser, new[]{ "LineWidth", "FieldLength", "FieldWidth", "BoundaryWidth", "RefereeWidth", "GoalWidth", "GoalDepth", "GoalWallWidth", "CenterCircleRadius", "DefenseRadius", "DefenseStretch", "FreeKickFromDefenseDist", "PenaltySpotFromFieldLineDist", "PenaltyLineFromSpotDist" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::RoboCup2014Legacy.Geometry.SSL_GeometryData), global::RoboCup2014Legacy.Geometry.SSL_GeometryData.Parser, new[]{ "Field", "Calib" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class SSL_GeometryFieldSize : pb::IMessage<SSL_GeometryFieldSize> {
    private static readonly pb::MessageParser<SSL_GeometryFieldSize> _parser = new pb::MessageParser<SSL_GeometryFieldSize>(() => new SSL_GeometryFieldSize());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<SSL_GeometryFieldSize> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::RoboCup2014Legacy.Geometry.MessagesRobocupSslGeometryLegacyReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SSL_GeometryFieldSize() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SSL_GeometryFieldSize(SSL_GeometryFieldSize other) : this() {
      lineWidth_ = other.lineWidth_;
      fieldLength_ = other.fieldLength_;
      fieldWidth_ = other.fieldWidth_;
      boundaryWidth_ = other.boundaryWidth_;
      refereeWidth_ = other.refereeWidth_;
      goalWidth_ = other.goalWidth_;
      goalDepth_ = other.goalDepth_;
      goalWallWidth_ = other.goalWallWidth_;
      centerCircleRadius_ = other.centerCircleRadius_;
      defenseRadius_ = other.defenseRadius_;
      defenseStretch_ = other.defenseStretch_;
      freeKickFromDefenseDist_ = other.freeKickFromDefenseDist_;
      penaltySpotFromFieldLineDist_ = other.penaltySpotFromFieldLineDist_;
      penaltyLineFromSpotDist_ = other.penaltyLineFromSpotDist_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SSL_GeometryFieldSize Clone() {
      return new SSL_GeometryFieldSize(this);
    }

    /// <summary>Field number for the "line_width" field.</summary>
    public const int LineWidthFieldNumber = 1;
    private int lineWidth_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int LineWidth {
      get { return lineWidth_; }
      set {
        lineWidth_ = value;
      }
    }

    /// <summary>Field number for the "field_length" field.</summary>
    public const int FieldLengthFieldNumber = 2;
    private int fieldLength_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int FieldLength {
      get { return fieldLength_; }
      set {
        fieldLength_ = value;
      }
    }

    /// <summary>Field number for the "field_width" field.</summary>
    public const int FieldWidthFieldNumber = 3;
    private int fieldWidth_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int FieldWidth {
      get { return fieldWidth_; }
      set {
        fieldWidth_ = value;
      }
    }

    /// <summary>Field number for the "boundary_width" field.</summary>
    public const int BoundaryWidthFieldNumber = 4;
    private int boundaryWidth_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int BoundaryWidth {
      get { return boundaryWidth_; }
      set {
        boundaryWidth_ = value;
      }
    }

    /// <summary>Field number for the "referee_width" field.</summary>
    public const int RefereeWidthFieldNumber = 5;
    private int refereeWidth_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int RefereeWidth {
      get { return refereeWidth_; }
      set {
        refereeWidth_ = value;
      }
    }

    /// <summary>Field number for the "goal_width" field.</summary>
    public const int GoalWidthFieldNumber = 6;
    private int goalWidth_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int GoalWidth {
      get { return goalWidth_; }
      set {
        goalWidth_ = value;
      }
    }

    /// <summary>Field number for the "goal_depth" field.</summary>
    public const int GoalDepthFieldNumber = 7;
    private int goalDepth_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int GoalDepth {
      get { return goalDepth_; }
      set {
        goalDepth_ = value;
      }
    }

    /// <summary>Field number for the "goal_wall_width" field.</summary>
    public const int GoalWallWidthFieldNumber = 8;
    private int goalWallWidth_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int GoalWallWidth {
      get { return goalWallWidth_; }
      set {
        goalWallWidth_ = value;
      }
    }

    /// <summary>Field number for the "center_circle_radius" field.</summary>
    public const int CenterCircleRadiusFieldNumber = 9;
    private int centerCircleRadius_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CenterCircleRadius {
      get { return centerCircleRadius_; }
      set {
        centerCircleRadius_ = value;
      }
    }

    /// <summary>Field number for the "defense_radius" field.</summary>
    public const int DefenseRadiusFieldNumber = 10;
    private int defenseRadius_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int DefenseRadius {
      get { return defenseRadius_; }
      set {
        defenseRadius_ = value;
      }
    }

    /// <summary>Field number for the "defense_stretch" field.</summary>
    public const int DefenseStretchFieldNumber = 11;
    private int defenseStretch_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int DefenseStretch {
      get { return defenseStretch_; }
      set {
        defenseStretch_ = value;
      }
    }

    /// <summary>Field number for the "free_kick_from_defense_dist" field.</summary>
    public const int FreeKickFromDefenseDistFieldNumber = 12;
    private int freeKickFromDefenseDist_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int FreeKickFromDefenseDist {
      get { return freeKickFromDefenseDist_; }
      set {
        freeKickFromDefenseDist_ = value;
      }
    }

    /// <summary>Field number for the "penalty_spot_from_field_line_dist" field.</summary>
    public const int PenaltySpotFromFieldLineDistFieldNumber = 13;
    private int penaltySpotFromFieldLineDist_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int PenaltySpotFromFieldLineDist {
      get { return penaltySpotFromFieldLineDist_; }
      set {
        penaltySpotFromFieldLineDist_ = value;
      }
    }

    /// <summary>Field number for the "penalty_line_from_spot_dist" field.</summary>
    public const int PenaltyLineFromSpotDistFieldNumber = 14;
    private int penaltyLineFromSpotDist_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int PenaltyLineFromSpotDist {
      get { return penaltyLineFromSpotDist_; }
      set {
        penaltyLineFromSpotDist_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as SSL_GeometryFieldSize);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(SSL_GeometryFieldSize other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (LineWidth != other.LineWidth) return false;
      if (FieldLength != other.FieldLength) return false;
      if (FieldWidth != other.FieldWidth) return false;
      if (BoundaryWidth != other.BoundaryWidth) return false;
      if (RefereeWidth != other.RefereeWidth) return false;
      if (GoalWidth != other.GoalWidth) return false;
      if (GoalDepth != other.GoalDepth) return false;
      if (GoalWallWidth != other.GoalWallWidth) return false;
      if (CenterCircleRadius != other.CenterCircleRadius) return false;
      if (DefenseRadius != other.DefenseRadius) return false;
      if (DefenseStretch != other.DefenseStretch) return false;
      if (FreeKickFromDefenseDist != other.FreeKickFromDefenseDist) return false;
      if (PenaltySpotFromFieldLineDist != other.PenaltySpotFromFieldLineDist) return false;
      if (PenaltyLineFromSpotDist != other.PenaltyLineFromSpotDist) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (LineWidth != 0) hash ^= LineWidth.GetHashCode();
      if (FieldLength != 0) hash ^= FieldLength.GetHashCode();
      if (FieldWidth != 0) hash ^= FieldWidth.GetHashCode();
      if (BoundaryWidth != 0) hash ^= BoundaryWidth.GetHashCode();
      if (RefereeWidth != 0) hash ^= RefereeWidth.GetHashCode();
      if (GoalWidth != 0) hash ^= GoalWidth.GetHashCode();
      if (GoalDepth != 0) hash ^= GoalDepth.GetHashCode();
      if (GoalWallWidth != 0) hash ^= GoalWallWidth.GetHashCode();
      if (CenterCircleRadius != 0) hash ^= CenterCircleRadius.GetHashCode();
      if (DefenseRadius != 0) hash ^= DefenseRadius.GetHashCode();
      if (DefenseStretch != 0) hash ^= DefenseStretch.GetHashCode();
      if (FreeKickFromDefenseDist != 0) hash ^= FreeKickFromDefenseDist.GetHashCode();
      if (PenaltySpotFromFieldLineDist != 0) hash ^= PenaltySpotFromFieldLineDist.GetHashCode();
      if (PenaltyLineFromSpotDist != 0) hash ^= PenaltyLineFromSpotDist.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (LineWidth != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(LineWidth);
      }
      if (FieldLength != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(FieldLength);
      }
      if (FieldWidth != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(FieldWidth);
      }
      if (BoundaryWidth != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(BoundaryWidth);
      }
      if (RefereeWidth != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(RefereeWidth);
      }
      if (GoalWidth != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(GoalWidth);
      }
      if (GoalDepth != 0) {
        output.WriteRawTag(56);
        output.WriteInt32(GoalDepth);
      }
      if (GoalWallWidth != 0) {
        output.WriteRawTag(64);
        output.WriteInt32(GoalWallWidth);
      }
      if (CenterCircleRadius != 0) {
        output.WriteRawTag(72);
        output.WriteInt32(CenterCircleRadius);
      }
      if (DefenseRadius != 0) {
        output.WriteRawTag(80);
        output.WriteInt32(DefenseRadius);
      }
      if (DefenseStretch != 0) {
        output.WriteRawTag(88);
        output.WriteInt32(DefenseStretch);
      }
      if (FreeKickFromDefenseDist != 0) {
        output.WriteRawTag(96);
        output.WriteInt32(FreeKickFromDefenseDist);
      }
      if (PenaltySpotFromFieldLineDist != 0) {
        output.WriteRawTag(104);
        output.WriteInt32(PenaltySpotFromFieldLineDist);
      }
      if (PenaltyLineFromSpotDist != 0) {
        output.WriteRawTag(112);
        output.WriteInt32(PenaltyLineFromSpotDist);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (LineWidth != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(LineWidth);
      }
      if (FieldLength != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(FieldLength);
      }
      if (FieldWidth != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(FieldWidth);
      }
      if (BoundaryWidth != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(BoundaryWidth);
      }
      if (RefereeWidth != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(RefereeWidth);
      }
      if (GoalWidth != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(GoalWidth);
      }
      if (GoalDepth != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(GoalDepth);
      }
      if (GoalWallWidth != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(GoalWallWidth);
      }
      if (CenterCircleRadius != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(CenterCircleRadius);
      }
      if (DefenseRadius != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(DefenseRadius);
      }
      if (DefenseStretch != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(DefenseStretch);
      }
      if (FreeKickFromDefenseDist != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(FreeKickFromDefenseDist);
      }
      if (PenaltySpotFromFieldLineDist != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(PenaltySpotFromFieldLineDist);
      }
      if (PenaltyLineFromSpotDist != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(PenaltyLineFromSpotDist);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(SSL_GeometryFieldSize other) {
      if (other == null) {
        return;
      }
      if (other.LineWidth != 0) {
        LineWidth = other.LineWidth;
      }
      if (other.FieldLength != 0) {
        FieldLength = other.FieldLength;
      }
      if (other.FieldWidth != 0) {
        FieldWidth = other.FieldWidth;
      }
      if (other.BoundaryWidth != 0) {
        BoundaryWidth = other.BoundaryWidth;
      }
      if (other.RefereeWidth != 0) {
        RefereeWidth = other.RefereeWidth;
      }
      if (other.GoalWidth != 0) {
        GoalWidth = other.GoalWidth;
      }
      if (other.GoalDepth != 0) {
        GoalDepth = other.GoalDepth;
      }
      if (other.GoalWallWidth != 0) {
        GoalWallWidth = other.GoalWallWidth;
      }
      if (other.CenterCircleRadius != 0) {
        CenterCircleRadius = other.CenterCircleRadius;
      }
      if (other.DefenseRadius != 0) {
        DefenseRadius = other.DefenseRadius;
      }
      if (other.DefenseStretch != 0) {
        DefenseStretch = other.DefenseStretch;
      }
      if (other.FreeKickFromDefenseDist != 0) {
        FreeKickFromDefenseDist = other.FreeKickFromDefenseDist;
      }
      if (other.PenaltySpotFromFieldLineDist != 0) {
        PenaltySpotFromFieldLineDist = other.PenaltySpotFromFieldLineDist;
      }
      if (other.PenaltyLineFromSpotDist != 0) {
        PenaltyLineFromSpotDist = other.PenaltyLineFromSpotDist;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            LineWidth = input.ReadInt32();
            break;
          }
          case 16: {
            FieldLength = input.ReadInt32();
            break;
          }
          case 24: {
            FieldWidth = input.ReadInt32();
            break;
          }
          case 32: {
            BoundaryWidth = input.ReadInt32();
            break;
          }
          case 40: {
            RefereeWidth = input.ReadInt32();
            break;
          }
          case 48: {
            GoalWidth = input.ReadInt32();
            break;
          }
          case 56: {
            GoalDepth = input.ReadInt32();
            break;
          }
          case 64: {
            GoalWallWidth = input.ReadInt32();
            break;
          }
          case 72: {
            CenterCircleRadius = input.ReadInt32();
            break;
          }
          case 80: {
            DefenseRadius = input.ReadInt32();
            break;
          }
          case 88: {
            DefenseStretch = input.ReadInt32();
            break;
          }
          case 96: {
            FreeKickFromDefenseDist = input.ReadInt32();
            break;
          }
          case 104: {
            PenaltySpotFromFieldLineDist = input.ReadInt32();
            break;
          }
          case 112: {
            PenaltyLineFromSpotDist = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  public sealed partial class SSL_GeometryData : pb::IMessage<SSL_GeometryData> {
    private static readonly pb::MessageParser<SSL_GeometryData> _parser = new pb::MessageParser<SSL_GeometryData>(() => new SSL_GeometryData());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<SSL_GeometryData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::RoboCup2014Legacy.Geometry.MessagesRobocupSslGeometryLegacyReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SSL_GeometryData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SSL_GeometryData(SSL_GeometryData other) : this() {
      Field = other.field_ != null ? other.Field.Clone() : null;
      calib_ = other.calib_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SSL_GeometryData Clone() {
      return new SSL_GeometryData(this);
    }

    /// <summary>Field number for the "field" field.</summary>
    public const int FieldFieldNumber = 1;
    private global::RoboCup2014Legacy.Geometry.SSL_GeometryFieldSize field_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::RoboCup2014Legacy.Geometry.SSL_GeometryFieldSize Field {
      get { return field_; }
      set {
        field_ = value;
      }
    }

    /// <summary>Field number for the "calib" field.</summary>
    public const int CalibFieldNumber = 2;
    private static readonly pb::FieldCodec<global::SSL_GeometryCameraCalibration> _repeated_calib_codec
        = pb::FieldCodec.ForMessage(18, global::SSL_GeometryCameraCalibration.Parser);
    private readonly pbc::RepeatedField<global::SSL_GeometryCameraCalibration> calib_ = new pbc::RepeatedField<global::SSL_GeometryCameraCalibration>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::SSL_GeometryCameraCalibration> Calib {
      get { return calib_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as SSL_GeometryData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(SSL_GeometryData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Field, other.Field)) return false;
      if(!calib_.Equals(other.calib_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (field_ != null) hash ^= Field.GetHashCode();
      hash ^= calib_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (field_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Field);
      }
      calib_.WriteTo(output, _repeated_calib_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (field_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Field);
      }
      size += calib_.CalculateSize(_repeated_calib_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(SSL_GeometryData other) {
      if (other == null) {
        return;
      }
      if (other.field_ != null) {
        if (field_ == null) {
          field_ = new global::RoboCup2014Legacy.Geometry.SSL_GeometryFieldSize();
        }
        Field.MergeFrom(other.Field);
      }
      calib_.Add(other.calib_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (field_ == null) {
              field_ = new global::RoboCup2014Legacy.Geometry.SSL_GeometryFieldSize();
            }
            input.ReadMessage(field_);
            break;
          }
          case 18: {
            calib_.AddEntriesFrom(input, _repeated_calib_codec);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
