// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: messages_robocup_ssl_geometry.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from messages_robocup_ssl_geometry.proto</summary>
public static partial class MessagesRobocupSslGeometryReflection {

  #region Descriptor
  /// <summary>File descriptor for messages_robocup_ssl_geometry.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static MessagesRobocupSslGeometryReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "CiNtZXNzYWdlc19yb2JvY3VwX3NzbF9nZW9tZXRyeS5wcm90byIgCghWZWN0",
          "b3IyZhIJCgF4GAEgASgCEgkKAXkYAiABKAIiZQoUU1NMX0ZpZWxkTGluZVNl",
          "Z21lbnQSDAoEbmFtZRgBIAEoCRIVCgJwMRgCIAEoCzIJLlZlY3RvcjJmEhUK",
          "AnAyGAMgASgLMgkuVmVjdG9yMmYSEQoJdGhpY2tuZXNzGAQgASgCInkKE1NT",
          "TF9GaWVsZENpY3VsYXJBcmMSDAoEbmFtZRgBIAEoCRIZCgZjZW50ZXIYAiAB",
          "KAsyCS5WZWN0b3IyZhIOCgZyYWRpdXMYAyABKAISCgoCYTEYBCABKAISCgoC",
          "YTIYBSABKAISEQoJdGhpY2tuZXNzGAYgASgCItgBChVTU0xfR2VvbWV0cnlG",
          "aWVsZFNpemUSFAoMZmllbGRfbGVuZ3RoGAEgASgFEhMKC2ZpZWxkX3dpZHRo",
          "GAIgASgFEhIKCmdvYWxfd2lkdGgYAyABKAUSEgoKZ29hbF9kZXB0aBgEIAEo",
          "BRIWCg5ib3VuZGFyeV93aWR0aBgFIAEoBRIqCgtmaWVsZF9saW5lcxgGIAMo",
          "CzIVLlNTTF9GaWVsZExpbmVTZWdtZW50EigKCmZpZWxkX2FyY3MYByADKAsy",
          "FC5TU0xfRmllbGRDaWN1bGFyQXJjIskCCh1TU0xfR2VvbWV0cnlDYW1lcmFD",
          "YWxpYnJhdGlvbhIRCgljYW1lcmFfaWQYASABKA0SFAoMZm9jYWxfbGVuZ3Ro",
          "GAIgASgCEhkKEXByaW5jaXBhbF9wb2ludF94GAMgASgCEhkKEXByaW5jaXBh",
          "bF9wb2ludF95GAQgASgCEhIKCmRpc3RvcnRpb24YBSABKAISCgoCcTAYBiAB",
          "KAISCgoCcTEYByABKAISCgoCcTIYCCABKAISCgoCcTMYCSABKAISCgoCdHgY",
          "CiABKAISCgoCdHkYCyABKAISCgoCdHoYDCABKAISHwoXZGVyaXZlZF9jYW1l",
          "cmFfd29ybGRfdHgYDSABKAISHwoXZGVyaXZlZF9jYW1lcmFfd29ybGRfdHkY",
          "DiABKAISHwoXZGVyaXZlZF9jYW1lcmFfd29ybGRfdHoYDyABKAIiaAoQU1NM",
          "X0dlb21ldHJ5RGF0YRIlCgVmaWVsZBgBIAEoCzIWLlNTTF9HZW9tZXRyeUZp",
          "ZWxkU2l6ZRItCgVjYWxpYhgCIAMoCzIeLlNTTF9HZW9tZXRyeUNhbWVyYUNh",
          "bGlicmF0aW9uYgZwcm90bzM="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::Vector2f), global::Vector2f.Parser, new[]{ "X", "Y" }, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::SSL_FieldLineSegment), global::SSL_FieldLineSegment.Parser, new[]{ "Name", "P1", "P2", "Thickness" }, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::SSL_FieldCicularArc), global::SSL_FieldCicularArc.Parser, new[]{ "Name", "Center", "Radius", "A1", "A2", "Thickness" }, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::SSL_GeometryFieldSize), global::SSL_GeometryFieldSize.Parser, new[]{ "FieldLength", "FieldWidth", "GoalWidth", "GoalDepth", "BoundaryWidth", "FieldLines", "FieldArcs" }, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::SSL_GeometryCameraCalibration), global::SSL_GeometryCameraCalibration.Parser, new[]{ "CameraId", "FocalLength", "PrincipalPointX", "PrincipalPointY", "Distortion", "Q0", "Q1", "Q2", "Q3", "Tx", "Ty", "Tz", "DerivedCameraWorldTx", "DerivedCameraWorldTy", "DerivedCameraWorldTz" }, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::SSL_GeometryData), global::SSL_GeometryData.Parser, new[]{ "Field", "Calib" }, null, null, null)
        }));
  }
  #endregion

}
#region Messages
/// <summary>
/// A 2D float vector.
/// </summary>
public sealed partial class Vector2f : pb::IMessage<Vector2f> {
  private static readonly pb::MessageParser<Vector2f> _parser = new pb::MessageParser<Vector2f>(() => new Vector2f());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<Vector2f> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::MessagesRobocupSslGeometryReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public Vector2f() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public Vector2f(Vector2f other) : this() {
    x_ = other.x_;
    y_ = other.y_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public Vector2f Clone() {
    return new Vector2f(this);
  }

  /// <summary>Field number for the "x" field.</summary>
  public const int XFieldNumber = 1;
  private float x_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public float X {
    get { return x_; }
    set {
      x_ = value;
    }
  }

  /// <summary>Field number for the "y" field.</summary>
  public const int YFieldNumber = 2;
  private float y_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public float Y {
    get { return y_; }
    set {
      y_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as Vector2f);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(Vector2f other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(X, other.X)) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Y, other.Y)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (X != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(X);
    if (Y != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Y);
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (X != 0F) {
      output.WriteRawTag(13);
      output.WriteFloat(X);
    }
    if (Y != 0F) {
      output.WriteRawTag(21);
      output.WriteFloat(Y);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (X != 0F) {
      size += 1 + 4;
    }
    if (Y != 0F) {
      size += 1 + 4;
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(Vector2f other) {
    if (other == null) {
      return;
    }
    if (other.X != 0F) {
      X = other.X;
    }
    if (other.Y != 0F) {
      Y = other.Y;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 13: {
          X = input.ReadFloat();
          break;
        }
        case 21: {
          Y = input.ReadFloat();
          break;
        }
      }
    }
  }

}

/// <summary>
/// Represents a field marking as a line segment represented by a start point p1,
/// and end point p2, and a line thickness. The start and end points are along
/// the center of the line, so the thickness of the line extends by thickness / 2
/// on either side of the line.
/// </summary>
public sealed partial class SSL_FieldLineSegment : pb::IMessage<SSL_FieldLineSegment> {
  private static readonly pb::MessageParser<SSL_FieldLineSegment> _parser = new pb::MessageParser<SSL_FieldLineSegment>(() => new SSL_FieldLineSegment());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<SSL_FieldLineSegment> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::MessagesRobocupSslGeometryReflection.Descriptor.MessageTypes[1]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public SSL_FieldLineSegment() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public SSL_FieldLineSegment(SSL_FieldLineSegment other) : this() {
    name_ = other.name_;
    P1 = other.p1_ != null ? other.P1.Clone() : null;
    P2 = other.p2_ != null ? other.P2.Clone() : null;
    thickness_ = other.thickness_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public SSL_FieldLineSegment Clone() {
    return new SSL_FieldLineSegment(this);
  }

  /// <summary>Field number for the "name" field.</summary>
  public const int NameFieldNumber = 1;
  private string name_ = "";
  /// <summary>
  /// Name of this field marking.
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Name {
    get { return name_; }
    set {
      name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "p1" field.</summary>
  public const int P1FieldNumber = 2;
  private global::Vector2f p1_;
  /// <summary>
  /// Start point of the line segment.
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::Vector2f P1 {
    get { return p1_; }
    set {
      p1_ = value;
    }
  }

  /// <summary>Field number for the "p2" field.</summary>
  public const int P2FieldNumber = 3;
  private global::Vector2f p2_;
  /// <summary>
  /// End point of the line segment.
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::Vector2f P2 {
    get { return p2_; }
    set {
      p2_ = value;
    }
  }

  /// <summary>Field number for the "thickness" field.</summary>
  public const int ThicknessFieldNumber = 4;
  private float thickness_;
  /// <summary>
  /// Thickness of the line segment.
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public float Thickness {
    get { return thickness_; }
    set {
      thickness_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as SSL_FieldLineSegment);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(SSL_FieldLineSegment other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Name != other.Name) return false;
    if (!object.Equals(P1, other.P1)) return false;
    if (!object.Equals(P2, other.P2)) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Thickness, other.Thickness)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (Name.Length != 0) hash ^= Name.GetHashCode();
    if (p1_ != null) hash ^= P1.GetHashCode();
    if (p2_ != null) hash ^= P2.GetHashCode();
    if (Thickness != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Thickness);
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (Name.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(Name);
    }
    if (p1_ != null) {
      output.WriteRawTag(18);
      output.WriteMessage(P1);
    }
    if (p2_ != null) {
      output.WriteRawTag(26);
      output.WriteMessage(P2);
    }
    if (Thickness != 0F) {
      output.WriteRawTag(37);
      output.WriteFloat(Thickness);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (Name.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
    }
    if (p1_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(P1);
    }
    if (p2_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(P2);
    }
    if (Thickness != 0F) {
      size += 1 + 4;
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(SSL_FieldLineSegment other) {
    if (other == null) {
      return;
    }
    if (other.Name.Length != 0) {
      Name = other.Name;
    }
    if (other.p1_ != null) {
      if (p1_ == null) {
        p1_ = new global::Vector2f();
      }
      P1.MergeFrom(other.P1);
    }
    if (other.p2_ != null) {
      if (p2_ == null) {
        p2_ = new global::Vector2f();
      }
      P2.MergeFrom(other.P2);
    }
    if (other.Thickness != 0F) {
      Thickness = other.Thickness;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          Name = input.ReadString();
          break;
        }
        case 18: {
          if (p1_ == null) {
            p1_ = new global::Vector2f();
          }
          input.ReadMessage(p1_);
          break;
        }
        case 26: {
          if (p2_ == null) {
            p2_ = new global::Vector2f();
          }
          input.ReadMessage(p2_);
          break;
        }
        case 37: {
          Thickness = input.ReadFloat();
          break;
        }
      }
    }
  }

}

/// <summary>
/// Represents a field marking as a circular arc segment represented by center point, a
/// start angle, an end angle, and an arc thickness.
/// </summary>
public sealed partial class SSL_FieldCicularArc : pb::IMessage<SSL_FieldCicularArc> {
  private static readonly pb::MessageParser<SSL_FieldCicularArc> _parser = new pb::MessageParser<SSL_FieldCicularArc>(() => new SSL_FieldCicularArc());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<SSL_FieldCicularArc> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::MessagesRobocupSslGeometryReflection.Descriptor.MessageTypes[2]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public SSL_FieldCicularArc() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public SSL_FieldCicularArc(SSL_FieldCicularArc other) : this() {
    name_ = other.name_;
    Center = other.center_ != null ? other.Center.Clone() : null;
    radius_ = other.radius_;
    a1_ = other.a1_;
    a2_ = other.a2_;
    thickness_ = other.thickness_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public SSL_FieldCicularArc Clone() {
    return new SSL_FieldCicularArc(this);
  }

  /// <summary>Field number for the "name" field.</summary>
  public const int NameFieldNumber = 1;
  private string name_ = "";
  /// <summary>
  /// Name of this field marking.
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Name {
    get { return name_; }
    set {
      name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "center" field.</summary>
  public const int CenterFieldNumber = 2;
  private global::Vector2f center_;
  /// <summary>
  /// Center point of the circular arc.
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::Vector2f Center {
    get { return center_; }
    set {
      center_ = value;
    }
  }

  /// <summary>Field number for the "radius" field.</summary>
  public const int RadiusFieldNumber = 3;
  private float radius_;
  /// <summary>
  /// Radius of the arc.
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public float Radius {
    get { return radius_; }
    set {
      radius_ = value;
    }
  }

  /// <summary>Field number for the "a1" field.</summary>
  public const int A1FieldNumber = 4;
  private float a1_;
  /// <summary>
  /// Start angle in counter-clockwise order.
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public float A1 {
    get { return a1_; }
    set {
      a1_ = value;
    }
  }

  /// <summary>Field number for the "a2" field.</summary>
  public const int A2FieldNumber = 5;
  private float a2_;
  /// <summary>
  /// End angle in counter-clockwise order.
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public float A2 {
    get { return a2_; }
    set {
      a2_ = value;
    }
  }

  /// <summary>Field number for the "thickness" field.</summary>
  public const int ThicknessFieldNumber = 6;
  private float thickness_;
  /// <summary>
  /// Thickness of the arc.
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public float Thickness {
    get { return thickness_; }
    set {
      thickness_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as SSL_FieldCicularArc);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(SSL_FieldCicularArc other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Name != other.Name) return false;
    if (!object.Equals(Center, other.Center)) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Radius, other.Radius)) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(A1, other.A1)) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(A2, other.A2)) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Thickness, other.Thickness)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (Name.Length != 0) hash ^= Name.GetHashCode();
    if (center_ != null) hash ^= Center.GetHashCode();
    if (Radius != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Radius);
    if (A1 != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(A1);
    if (A2 != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(A2);
    if (Thickness != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Thickness);
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (Name.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(Name);
    }
    if (center_ != null) {
      output.WriteRawTag(18);
      output.WriteMessage(Center);
    }
    if (Radius != 0F) {
      output.WriteRawTag(29);
      output.WriteFloat(Radius);
    }
    if (A1 != 0F) {
      output.WriteRawTag(37);
      output.WriteFloat(A1);
    }
    if (A2 != 0F) {
      output.WriteRawTag(45);
      output.WriteFloat(A2);
    }
    if (Thickness != 0F) {
      output.WriteRawTag(53);
      output.WriteFloat(Thickness);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (Name.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
    }
    if (center_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Center);
    }
    if (Radius != 0F) {
      size += 1 + 4;
    }
    if (A1 != 0F) {
      size += 1 + 4;
    }
    if (A2 != 0F) {
      size += 1 + 4;
    }
    if (Thickness != 0F) {
      size += 1 + 4;
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(SSL_FieldCicularArc other) {
    if (other == null) {
      return;
    }
    if (other.Name.Length != 0) {
      Name = other.Name;
    }
    if (other.center_ != null) {
      if (center_ == null) {
        center_ = new global::Vector2f();
      }
      Center.MergeFrom(other.Center);
    }
    if (other.Radius != 0F) {
      Radius = other.Radius;
    }
    if (other.A1 != 0F) {
      A1 = other.A1;
    }
    if (other.A2 != 0F) {
      A2 = other.A2;
    }
    if (other.Thickness != 0F) {
      Thickness = other.Thickness;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          Name = input.ReadString();
          break;
        }
        case 18: {
          if (center_ == null) {
            center_ = new global::Vector2f();
          }
          input.ReadMessage(center_);
          break;
        }
        case 29: {
          Radius = input.ReadFloat();
          break;
        }
        case 37: {
          A1 = input.ReadFloat();
          break;
        }
        case 45: {
          A2 = input.ReadFloat();
          break;
        }
        case 53: {
          Thickness = input.ReadFloat();
          break;
        }
      }
    }
  }

}

public sealed partial class SSL_GeometryFieldSize : pb::IMessage<SSL_GeometryFieldSize> {
  private static readonly pb::MessageParser<SSL_GeometryFieldSize> _parser = new pb::MessageParser<SSL_GeometryFieldSize>(() => new SSL_GeometryFieldSize());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<SSL_GeometryFieldSize> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::MessagesRobocupSslGeometryReflection.Descriptor.MessageTypes[3]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public SSL_GeometryFieldSize() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public SSL_GeometryFieldSize(SSL_GeometryFieldSize other) : this() {
    fieldLength_ = other.fieldLength_;
    fieldWidth_ = other.fieldWidth_;
    goalWidth_ = other.goalWidth_;
    goalDepth_ = other.goalDepth_;
    boundaryWidth_ = other.boundaryWidth_;
    fieldLines_ = other.fieldLines_.Clone();
    fieldArcs_ = other.fieldArcs_.Clone();
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public SSL_GeometryFieldSize Clone() {
    return new SSL_GeometryFieldSize(this);
  }

  /// <summary>Field number for the "field_length" field.</summary>
  public const int FieldLengthFieldNumber = 1;
  private int fieldLength_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int FieldLength {
    get { return fieldLength_; }
    set {
      fieldLength_ = value;
    }
  }

  /// <summary>Field number for the "field_width" field.</summary>
  public const int FieldWidthFieldNumber = 2;
  private int fieldWidth_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int FieldWidth {
    get { return fieldWidth_; }
    set {
      fieldWidth_ = value;
    }
  }

  /// <summary>Field number for the "goal_width" field.</summary>
  public const int GoalWidthFieldNumber = 3;
  private int goalWidth_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int GoalWidth {
    get { return goalWidth_; }
    set {
      goalWidth_ = value;
    }
  }

  /// <summary>Field number for the "goal_depth" field.</summary>
  public const int GoalDepthFieldNumber = 4;
  private int goalDepth_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int GoalDepth {
    get { return goalDepth_; }
    set {
      goalDepth_ = value;
    }
  }

  /// <summary>Field number for the "boundary_width" field.</summary>
  public const int BoundaryWidthFieldNumber = 5;
  private int boundaryWidth_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int BoundaryWidth {
    get { return boundaryWidth_; }
    set {
      boundaryWidth_ = value;
    }
  }

  /// <summary>Field number for the "field_lines" field.</summary>
  public const int FieldLinesFieldNumber = 6;
  private static readonly pb::FieldCodec<global::SSL_FieldLineSegment> _repeated_fieldLines_codec
      = pb::FieldCodec.ForMessage(50, global::SSL_FieldLineSegment.Parser);
  private readonly pbc::RepeatedField<global::SSL_FieldLineSegment> fieldLines_ = new pbc::RepeatedField<global::SSL_FieldLineSegment>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public pbc::RepeatedField<global::SSL_FieldLineSegment> FieldLines {
    get { return fieldLines_; }
  }

  /// <summary>Field number for the "field_arcs" field.</summary>
  public const int FieldArcsFieldNumber = 7;
  private static readonly pb::FieldCodec<global::SSL_FieldCicularArc> _repeated_fieldArcs_codec
      = pb::FieldCodec.ForMessage(58, global::SSL_FieldCicularArc.Parser);
  private readonly pbc::RepeatedField<global::SSL_FieldCicularArc> fieldArcs_ = new pbc::RepeatedField<global::SSL_FieldCicularArc>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public pbc::RepeatedField<global::SSL_FieldCicularArc> FieldArcs {
    get { return fieldArcs_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as SSL_GeometryFieldSize);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(SSL_GeometryFieldSize other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (FieldLength != other.FieldLength) return false;
    if (FieldWidth != other.FieldWidth) return false;
    if (GoalWidth != other.GoalWidth) return false;
    if (GoalDepth != other.GoalDepth) return false;
    if (BoundaryWidth != other.BoundaryWidth) return false;
    if(!fieldLines_.Equals(other.fieldLines_)) return false;
    if(!fieldArcs_.Equals(other.fieldArcs_)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (FieldLength != 0) hash ^= FieldLength.GetHashCode();
    if (FieldWidth != 0) hash ^= FieldWidth.GetHashCode();
    if (GoalWidth != 0) hash ^= GoalWidth.GetHashCode();
    if (GoalDepth != 0) hash ^= GoalDepth.GetHashCode();
    if (BoundaryWidth != 0) hash ^= BoundaryWidth.GetHashCode();
    hash ^= fieldLines_.GetHashCode();
    hash ^= fieldArcs_.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (FieldLength != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(FieldLength);
    }
    if (FieldWidth != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(FieldWidth);
    }
    if (GoalWidth != 0) {
      output.WriteRawTag(24);
      output.WriteInt32(GoalWidth);
    }
    if (GoalDepth != 0) {
      output.WriteRawTag(32);
      output.WriteInt32(GoalDepth);
    }
    if (BoundaryWidth != 0) {
      output.WriteRawTag(40);
      output.WriteInt32(BoundaryWidth);
    }
    fieldLines_.WriteTo(output, _repeated_fieldLines_codec);
    fieldArcs_.WriteTo(output, _repeated_fieldArcs_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (FieldLength != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(FieldLength);
    }
    if (FieldWidth != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(FieldWidth);
    }
    if (GoalWidth != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(GoalWidth);
    }
    if (GoalDepth != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(GoalDepth);
    }
    if (BoundaryWidth != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(BoundaryWidth);
    }
    size += fieldLines_.CalculateSize(_repeated_fieldLines_codec);
    size += fieldArcs_.CalculateSize(_repeated_fieldArcs_codec);
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(SSL_GeometryFieldSize other) {
    if (other == null) {
      return;
    }
    if (other.FieldLength != 0) {
      FieldLength = other.FieldLength;
    }
    if (other.FieldWidth != 0) {
      FieldWidth = other.FieldWidth;
    }
    if (other.GoalWidth != 0) {
      GoalWidth = other.GoalWidth;
    }
    if (other.GoalDepth != 0) {
      GoalDepth = other.GoalDepth;
    }
    if (other.BoundaryWidth != 0) {
      BoundaryWidth = other.BoundaryWidth;
    }
    fieldLines_.Add(other.fieldLines_);
    fieldArcs_.Add(other.fieldArcs_);
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          FieldLength = input.ReadInt32();
          break;
        }
        case 16: {
          FieldWidth = input.ReadInt32();
          break;
        }
        case 24: {
          GoalWidth = input.ReadInt32();
          break;
        }
        case 32: {
          GoalDepth = input.ReadInt32();
          break;
        }
        case 40: {
          BoundaryWidth = input.ReadInt32();
          break;
        }
        case 50: {
          fieldLines_.AddEntriesFrom(input, _repeated_fieldLines_codec);
          break;
        }
        case 58: {
          fieldArcs_.AddEntriesFrom(input, _repeated_fieldArcs_codec);
          break;
        }
      }
    }
  }

}

public sealed partial class SSL_GeometryCameraCalibration : pb::IMessage<SSL_GeometryCameraCalibration> {
  private static readonly pb::MessageParser<SSL_GeometryCameraCalibration> _parser = new pb::MessageParser<SSL_GeometryCameraCalibration>(() => new SSL_GeometryCameraCalibration());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<SSL_GeometryCameraCalibration> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::MessagesRobocupSslGeometryReflection.Descriptor.MessageTypes[4]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public SSL_GeometryCameraCalibration() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public SSL_GeometryCameraCalibration(SSL_GeometryCameraCalibration other) : this() {
    cameraId_ = other.cameraId_;
    focalLength_ = other.focalLength_;
    principalPointX_ = other.principalPointX_;
    principalPointY_ = other.principalPointY_;
    distortion_ = other.distortion_;
    q0_ = other.q0_;
    q1_ = other.q1_;
    q2_ = other.q2_;
    q3_ = other.q3_;
    tx_ = other.tx_;
    ty_ = other.ty_;
    tz_ = other.tz_;
    derivedCameraWorldTx_ = other.derivedCameraWorldTx_;
    derivedCameraWorldTy_ = other.derivedCameraWorldTy_;
    derivedCameraWorldTz_ = other.derivedCameraWorldTz_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public SSL_GeometryCameraCalibration Clone() {
    return new SSL_GeometryCameraCalibration(this);
  }

  /// <summary>Field number for the "camera_id" field.</summary>
  public const int CameraIdFieldNumber = 1;
  private uint cameraId_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public uint CameraId {
    get { return cameraId_; }
    set {
      cameraId_ = value;
    }
  }

  /// <summary>Field number for the "focal_length" field.</summary>
  public const int FocalLengthFieldNumber = 2;
  private float focalLength_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public float FocalLength {
    get { return focalLength_; }
    set {
      focalLength_ = value;
    }
  }

  /// <summary>Field number for the "principal_point_x" field.</summary>
  public const int PrincipalPointXFieldNumber = 3;
  private float principalPointX_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public float PrincipalPointX {
    get { return principalPointX_; }
    set {
      principalPointX_ = value;
    }
  }

  /// <summary>Field number for the "principal_point_y" field.</summary>
  public const int PrincipalPointYFieldNumber = 4;
  private float principalPointY_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public float PrincipalPointY {
    get { return principalPointY_; }
    set {
      principalPointY_ = value;
    }
  }

  /// <summary>Field number for the "distortion" field.</summary>
  public const int DistortionFieldNumber = 5;
  private float distortion_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public float Distortion {
    get { return distortion_; }
    set {
      distortion_ = value;
    }
  }

  /// <summary>Field number for the "q0" field.</summary>
  public const int Q0FieldNumber = 6;
  private float q0_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public float Q0 {
    get { return q0_; }
    set {
      q0_ = value;
    }
  }

  /// <summary>Field number for the "q1" field.</summary>
  public const int Q1FieldNumber = 7;
  private float q1_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public float Q1 {
    get { return q1_; }
    set {
      q1_ = value;
    }
  }

  /// <summary>Field number for the "q2" field.</summary>
  public const int Q2FieldNumber = 8;
  private float q2_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public float Q2 {
    get { return q2_; }
    set {
      q2_ = value;
    }
  }

  /// <summary>Field number for the "q3" field.</summary>
  public const int Q3FieldNumber = 9;
  private float q3_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public float Q3 {
    get { return q3_; }
    set {
      q3_ = value;
    }
  }

  /// <summary>Field number for the "tx" field.</summary>
  public const int TxFieldNumber = 10;
  private float tx_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public float Tx {
    get { return tx_; }
    set {
      tx_ = value;
    }
  }

  /// <summary>Field number for the "ty" field.</summary>
  public const int TyFieldNumber = 11;
  private float ty_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public float Ty {
    get { return ty_; }
    set {
      ty_ = value;
    }
  }

  /// <summary>Field number for the "tz" field.</summary>
  public const int TzFieldNumber = 12;
  private float tz_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public float Tz {
    get { return tz_; }
    set {
      tz_ = value;
    }
  }

  /// <summary>Field number for the "derived_camera_world_tx" field.</summary>
  public const int DerivedCameraWorldTxFieldNumber = 13;
  private float derivedCameraWorldTx_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public float DerivedCameraWorldTx {
    get { return derivedCameraWorldTx_; }
    set {
      derivedCameraWorldTx_ = value;
    }
  }

  /// <summary>Field number for the "derived_camera_world_ty" field.</summary>
  public const int DerivedCameraWorldTyFieldNumber = 14;
  private float derivedCameraWorldTy_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public float DerivedCameraWorldTy {
    get { return derivedCameraWorldTy_; }
    set {
      derivedCameraWorldTy_ = value;
    }
  }

  /// <summary>Field number for the "derived_camera_world_tz" field.</summary>
  public const int DerivedCameraWorldTzFieldNumber = 15;
  private float derivedCameraWorldTz_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public float DerivedCameraWorldTz {
    get { return derivedCameraWorldTz_; }
    set {
      derivedCameraWorldTz_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as SSL_GeometryCameraCalibration);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(SSL_GeometryCameraCalibration other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (CameraId != other.CameraId) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(FocalLength, other.FocalLength)) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(PrincipalPointX, other.PrincipalPointX)) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(PrincipalPointY, other.PrincipalPointY)) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Distortion, other.Distortion)) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Q0, other.Q0)) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Q1, other.Q1)) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Q2, other.Q2)) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Q3, other.Q3)) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Tx, other.Tx)) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Ty, other.Ty)) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Tz, other.Tz)) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(DerivedCameraWorldTx, other.DerivedCameraWorldTx)) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(DerivedCameraWorldTy, other.DerivedCameraWorldTy)) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(DerivedCameraWorldTz, other.DerivedCameraWorldTz)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (CameraId != 0) hash ^= CameraId.GetHashCode();
    if (FocalLength != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(FocalLength);
    if (PrincipalPointX != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(PrincipalPointX);
    if (PrincipalPointY != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(PrincipalPointY);
    if (Distortion != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Distortion);
    if (Q0 != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Q0);
    if (Q1 != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Q1);
    if (Q2 != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Q2);
    if (Q3 != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Q3);
    if (Tx != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Tx);
    if (Ty != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Ty);
    if (Tz != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Tz);
    if (DerivedCameraWorldTx != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(DerivedCameraWorldTx);
    if (DerivedCameraWorldTy != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(DerivedCameraWorldTy);
    if (DerivedCameraWorldTz != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(DerivedCameraWorldTz);
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (CameraId != 0) {
      output.WriteRawTag(8);
      output.WriteUInt32(CameraId);
    }
    if (FocalLength != 0F) {
      output.WriteRawTag(21);
      output.WriteFloat(FocalLength);
    }
    if (PrincipalPointX != 0F) {
      output.WriteRawTag(29);
      output.WriteFloat(PrincipalPointX);
    }
    if (PrincipalPointY != 0F) {
      output.WriteRawTag(37);
      output.WriteFloat(PrincipalPointY);
    }
    if (Distortion != 0F) {
      output.WriteRawTag(45);
      output.WriteFloat(Distortion);
    }
    if (Q0 != 0F) {
      output.WriteRawTag(53);
      output.WriteFloat(Q0);
    }
    if (Q1 != 0F) {
      output.WriteRawTag(61);
      output.WriteFloat(Q1);
    }
    if (Q2 != 0F) {
      output.WriteRawTag(69);
      output.WriteFloat(Q2);
    }
    if (Q3 != 0F) {
      output.WriteRawTag(77);
      output.WriteFloat(Q3);
    }
    if (Tx != 0F) {
      output.WriteRawTag(85);
      output.WriteFloat(Tx);
    }
    if (Ty != 0F) {
      output.WriteRawTag(93);
      output.WriteFloat(Ty);
    }
    if (Tz != 0F) {
      output.WriteRawTag(101);
      output.WriteFloat(Tz);
    }
    if (DerivedCameraWorldTx != 0F) {
      output.WriteRawTag(109);
      output.WriteFloat(DerivedCameraWorldTx);
    }
    if (DerivedCameraWorldTy != 0F) {
      output.WriteRawTag(117);
      output.WriteFloat(DerivedCameraWorldTy);
    }
    if (DerivedCameraWorldTz != 0F) {
      output.WriteRawTag(125);
      output.WriteFloat(DerivedCameraWorldTz);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (CameraId != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(CameraId);
    }
    if (FocalLength != 0F) {
      size += 1 + 4;
    }
    if (PrincipalPointX != 0F) {
      size += 1 + 4;
    }
    if (PrincipalPointY != 0F) {
      size += 1 + 4;
    }
    if (Distortion != 0F) {
      size += 1 + 4;
    }
    if (Q0 != 0F) {
      size += 1 + 4;
    }
    if (Q1 != 0F) {
      size += 1 + 4;
    }
    if (Q2 != 0F) {
      size += 1 + 4;
    }
    if (Q3 != 0F) {
      size += 1 + 4;
    }
    if (Tx != 0F) {
      size += 1 + 4;
    }
    if (Ty != 0F) {
      size += 1 + 4;
    }
    if (Tz != 0F) {
      size += 1 + 4;
    }
    if (DerivedCameraWorldTx != 0F) {
      size += 1 + 4;
    }
    if (DerivedCameraWorldTy != 0F) {
      size += 1 + 4;
    }
    if (DerivedCameraWorldTz != 0F) {
      size += 1 + 4;
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(SSL_GeometryCameraCalibration other) {
    if (other == null) {
      return;
    }
    if (other.CameraId != 0) {
      CameraId = other.CameraId;
    }
    if (other.FocalLength != 0F) {
      FocalLength = other.FocalLength;
    }
    if (other.PrincipalPointX != 0F) {
      PrincipalPointX = other.PrincipalPointX;
    }
    if (other.PrincipalPointY != 0F) {
      PrincipalPointY = other.PrincipalPointY;
    }
    if (other.Distortion != 0F) {
      Distortion = other.Distortion;
    }
    if (other.Q0 != 0F) {
      Q0 = other.Q0;
    }
    if (other.Q1 != 0F) {
      Q1 = other.Q1;
    }
    if (other.Q2 != 0F) {
      Q2 = other.Q2;
    }
    if (other.Q3 != 0F) {
      Q3 = other.Q3;
    }
    if (other.Tx != 0F) {
      Tx = other.Tx;
    }
    if (other.Ty != 0F) {
      Ty = other.Ty;
    }
    if (other.Tz != 0F) {
      Tz = other.Tz;
    }
    if (other.DerivedCameraWorldTx != 0F) {
      DerivedCameraWorldTx = other.DerivedCameraWorldTx;
    }
    if (other.DerivedCameraWorldTy != 0F) {
      DerivedCameraWorldTy = other.DerivedCameraWorldTy;
    }
    if (other.DerivedCameraWorldTz != 0F) {
      DerivedCameraWorldTz = other.DerivedCameraWorldTz;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          CameraId = input.ReadUInt32();
          break;
        }
        case 21: {
          FocalLength = input.ReadFloat();
          break;
        }
        case 29: {
          PrincipalPointX = input.ReadFloat();
          break;
        }
        case 37: {
          PrincipalPointY = input.ReadFloat();
          break;
        }
        case 45: {
          Distortion = input.ReadFloat();
          break;
        }
        case 53: {
          Q0 = input.ReadFloat();
          break;
        }
        case 61: {
          Q1 = input.ReadFloat();
          break;
        }
        case 69: {
          Q2 = input.ReadFloat();
          break;
        }
        case 77: {
          Q3 = input.ReadFloat();
          break;
        }
        case 85: {
          Tx = input.ReadFloat();
          break;
        }
        case 93: {
          Ty = input.ReadFloat();
          break;
        }
        case 101: {
          Tz = input.ReadFloat();
          break;
        }
        case 109: {
          DerivedCameraWorldTx = input.ReadFloat();
          break;
        }
        case 117: {
          DerivedCameraWorldTy = input.ReadFloat();
          break;
        }
        case 125: {
          DerivedCameraWorldTz = input.ReadFloat();
          break;
        }
      }
    }
  }

}

public sealed partial class SSL_GeometryData : pb::IMessage<SSL_GeometryData> {
  private static readonly pb::MessageParser<SSL_GeometryData> _parser = new pb::MessageParser<SSL_GeometryData>(() => new SSL_GeometryData());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<SSL_GeometryData> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::MessagesRobocupSslGeometryReflection.Descriptor.MessageTypes[5]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public SSL_GeometryData() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public SSL_GeometryData(SSL_GeometryData other) : this() {
    Field = other.field_ != null ? other.Field.Clone() : null;
    calib_ = other.calib_.Clone();
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public SSL_GeometryData Clone() {
    return new SSL_GeometryData(this);
  }

  /// <summary>Field number for the "field" field.</summary>
  public const int FieldFieldNumber = 1;
  private global::SSL_GeometryFieldSize field_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::SSL_GeometryFieldSize Field {
    get { return field_; }
    set {
      field_ = value;
    }
  }

  /// <summary>Field number for the "calib" field.</summary>
  public const int CalibFieldNumber = 2;
  private static readonly pb::FieldCodec<global::SSL_GeometryCameraCalibration> _repeated_calib_codec
      = pb::FieldCodec.ForMessage(18, global::SSL_GeometryCameraCalibration.Parser);
  private readonly pbc::RepeatedField<global::SSL_GeometryCameraCalibration> calib_ = new pbc::RepeatedField<global::SSL_GeometryCameraCalibration>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public pbc::RepeatedField<global::SSL_GeometryCameraCalibration> Calib {
    get { return calib_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as SSL_GeometryData);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(SSL_GeometryData other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (!object.Equals(Field, other.Field)) return false;
    if(!calib_.Equals(other.calib_)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (field_ != null) hash ^= Field.GetHashCode();
    hash ^= calib_.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (field_ != null) {
      output.WriteRawTag(10);
      output.WriteMessage(Field);
    }
    calib_.WriteTo(output, _repeated_calib_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (field_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Field);
    }
    size += calib_.CalculateSize(_repeated_calib_codec);
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(SSL_GeometryData other) {
    if (other == null) {
      return;
    }
    if (other.field_ != null) {
      if (field_ == null) {
        field_ = new global::SSL_GeometryFieldSize();
      }
      Field.MergeFrom(other.Field);
    }
    calib_.Add(other.calib_);
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          if (field_ == null) {
            field_ = new global::SSL_GeometryFieldSize();
          }
          input.ReadMessage(field_);
          break;
        }
        case 18: {
          calib_.AddEntriesFrom(input, _repeated_calib_codec);
          break;
        }
      }
    }
  }

}

#endregion


#endregion Designer generated code
